### PR TITLE
Feature : pass parameters as html data-* attributes

### PR DESCRIPTION
**Pull request by BenTalagan**
Hi!

This really simple PR adds the ability to pass jquery mosaic params as html data-* attributes, as it is often the case with such librairies.

Ex : 

```
<div id="#mymosaic" data-inner-gap="25" data-max-row-height-policy="crop"> 
...
</div>
```
This can be convenient when generating the mosaics from frameworks (rails, django, symphony, etc).
Parameter names inflection (dashes, capital case, etc) is done automatically by jquery through the **data** function so it simplifies the code and offers better compliance.

I haven't updated the version number, nor the example directory (I could not find how to make it to work). Minified version was generated with : 

```
uglifyjs jquery.mosaic.js -c -m -o jquery.mosaic.min.js
```

Could be nice to have just a little bit of documentation for developers (and build scripts!) ;)

Cheers, 
Ben

### CODE REVIEW

**Comment by tin-cat** [comment]
Thank you, really nice feature, and elegantly implemented, thanks! Will update the documentation accordingly, and also take a look at your suggestions. So much thaaanks! Meow!

**Comment by tin-cat** [comment]
Hi Ben!

I reviewed your changes and they look really great! I've accepted the push and made some modifications because I found that data attributes weren't applied properly because of upper/lowecase differences in the option's names. Had to implement a little trick to make it work.

I've also found a workaround to solve the floating point problem with jQuery versions < 3, as found on this article: https://glen.codes/getting-the-subpixel-width-of-an-element (Since jQuery doesn't needs to take into account padding, margins and other box-related sizes, I've simplified it to just a couple of lines of code.

Also added some additional documentation for developers about generating minified JS & CSS as per your suggestion, thanks!

Take a look at the branch here if you want! https://github.com/tin-cat/jquery-mosaic/tree/bug/floating_point_width

Thanks!

**Comment by BenTalagan** [comment]
Hi Lorenzo!

No problem, and thank you first for this great jquery plugin! These issues regarding parameter syntax case are sometimes really annoying, but should be solved easily if sticking to the most used formats for each language (with dashes for html, camelCase for js, etc). It seems a bit cryptic to me why you had to write a patch on that part - is it because you were expecting parameters to be passed as data-fooParameterSyntax instead of data-foo-parameter-syntax (or maybe you wanted to handle all kinds of syntax) ?

The $("...").css("width") trick seems cool ; I hope it won't break the plugin since everything is based on that width value :)

And thank you so much for the documentation!

Cheers!
Ben

**Comment by tin-cat** [comment]
Hi Ben,

Yes! Since the plugin works with the parameters in the camelCase format, and since HTML data properties are always converted to lowercase, I had to match the data-* to the parameters on the plugin in order to assign them. Another solution would be to change all the parameters in the plugin itself to be lowercase, but I thought that would break many implementations that have already been done, and I like to use camelCase for js.

You’re right about the .css(‘width’) instead of using .width(), I don’t really remember why I used this approach! As per the jQuery documentation, it should work nice, but the recommended approach is .width(), I should take a look at it and try to switch to the recommended version for standardization.

Thanks for the recommendations! Cheers!

**Comment by BenTalagan** [comment]
> Yes! Since the plugin works with the parameters in the camelCase format, and since HTML data properties are always converted to lowercase, I had to match the data-* to the parameters on the plugin in order to assign them. Another solution would be to change all the parameters in the plugin itself to be lowercase, but I thought that would break many implementations that have already been done, and I like to use camelCase for js.

Ok, I see! My initial idea was simply to force everyone using this new feature to stick to a clean data-* lower case syntax with dashes, putting the dashes at correct places. For example, if using : 

```HTML
<div id="mymosaic" data-inner-gap="25" data-max-row-height-policy="crop"> 
...
</div>
````

the jquery "data" function automagically returns:

```javascript
$("#mymosaic").data()

{maxRowHeightPolicy: "crop", innerGap: 25}
```
with the correct casing.

That's why I was a bit astonished that you had to write a patch, except in the case where you wanted to also handle such a syntax : 

```HTML
<div id="mymosaic" data-innerGap="25" data-maxRowHeightPolicy="crop"> 
...
</div>
````

which is understandable :)

Cheers!

**Comment by tin-cat** [comment]
I understand! I think with a little more trickery on the code that converts data-* parameters to plugin parameters, we could allow both data-max-row-height-policy and data-maxRowHeightPolicy HTML attributes, so both camelCase standard and HTML standard will be accepted. Will take a look at this!

Thnx!

**Comment by tin-cat** [comment]
Hi Ben!

You were right from the beggining! We didn’t need any trickery to convert html-* parameters to javascript standard, turns out jQuery does it rightaway, see, from the JQuery documentation:

"jQuery 3 changes the behavior of this method to align it to the Dataset API specifications <https://www.w3.org/TR/html5/dom.html#dom-dataset>. Specifically, jQuery 3 transforms every two-character sequence of "-" (U+002D) followed by a lowercase ASCII letter by the uppercase version of the letter as per definition of the algorithm of the Dataset API <https://www.w3.org/TR/html5/dom.html#dom-dataset>.”

(Here: https://api.jquery.com/data/ <https://api.jquery.com/data/>)

So yes, for example, when passing an HTML parameter like data-inner-gap=“10”, when getting it with the .data() jQuery method, it gets converted to innerGap, so all I had to do is, as you first suggested:

base.options = o = $.extend({}, $.Mosaic.defaults, base.$el.data(), options);

And that’s all!

Thanks for your ideas!

**Pull request merged**
